version: '3.1'

services:
  api:
    build:
      context: .
      target: env
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - 'db_data:/var/lib/postgresql/data'
      - './init-db/:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_DB: stories
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data:
    driver: local
